; Default environment settings
[platformio]
default_envs = waveshare-esp32s3-touch-amoled-164
build_cache_dir = ./firmware_cache/

[env:base]
; platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.35/platform-espressif32.zip
platform = platformio/espressif32 @ ^6.12.0
framework = espidf
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_upload.flash_size = 16MB

lib_deps = 
    lvgl/lvgl @ ^9.4.0
    vortigont/esp32-flashz # 1.1.5

    https://github.com/esp-arduino-libs/ESP32_Display_Panel.git # v1.0.4
    https://github.com/esp-arduino-libs/esp-lib-utils.git#v0.3.0
    https://github.com/esp-arduino-libs/ESP32_IO_Expander.git#v1.1.1
    ; https://github.com/esp-arduino-libs/ESP32_Button.git
    ; https://github.com/esp-arduino-libs/ESP32_Knob.git

extra_scripts = 
    tools/build-scripts/pre_build.py
    tools/build-scripts/post_build.py
    tools/build-scripts/custom_targets.py

; Custom partition table for delta OTA updates
board_build.partitions = partitions.csv

; Include local components for delta OTA
lib_extra_dirs = components

; Upload via USB settings
upload_speed = 921600
; upload_port = /dev/cu.usbmodem*

; Monitor settings  
monitor_speed = 115200
; monitor_port = /dev/cu.usbmodem*

build_unflags =
    -Werror # avoid error in esp_driver_i2c

build_flags =
    -Iinclude
    -Ofast
    ; -Wall
    -Wno-error=maybe-uninitialized # Avoid error in esp_driver_i2c/i2c_master.c:898
    '-D LV_CONF_PATH="${platformio.include_dir}/lv_conf.h"'
    ; -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -DNO_GLOBAL_UPDATE     ; Required by esp32-flashz
    -DFZ_NOHTTPCLIENT      ; Disable HTTP client (BLE only)
    -DESP_IDF_VERSION_MAJOR=5
    -DESP32S3
[env:waveshare-esp32s3-touch-amoled-164]
extends = env:base

[env:waveshare-esp32s3-touch-amoled-164-debug]
extends = env:waveshare-esp32s3-touch-amoled-164
build_type = debug
build_flags = 
    ${env:waveshare-esp32s3-touch-amoled-164.build_flags}
    -DUI_DEBUG_SERIAL_DELAY_MS=2000

; Suppress Wire library logs to suppress known requestFrom(): i2cWriteReadNonStop returned Error -1
; messages popping while polling the touchscreen controller. We have to poll
; because the touchscreen does not support interrupts.
monitor_filters = esp32_exception_decoder, default, hiding_filter
monitor_options =
    --filter hiding_filter:--regex ".*i2cWriteReadNonStop.*" --invert

[env:waveshare-esp32s3-touch-amoled-164-mock]
extends = env:waveshare-esp32s3-touch-amoled-164-debug

build_flags = 
    ${env:waveshare-esp32s3-touch-amoled-164.build_flags}
    -DMOCK_BUILD
    -DDEBUG_ENABLE_LOADCELL_MOCK=1
    -DDEBUG_ENABLE_GRINDER_BACKGROUND_INDICATOR=1

[env:viewesmart-touch-21round]
extends = env:base
build_type = debug

board = esp32-s3-devkitc-1
; board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.psram_clock = 80000000
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_upload.maximum_ram_size = 327680

build_flags = 
    ${env:waveshare-esp32s3-touch-amoled-164.build_flags}
    -DDISPLAY_PROFILE=DisplayProfile::VIEWE_TOUCH_ST7701S_ROUND_21
    -DENABLE_FPS_OVERLAY=1
    -LV_COLOR_16_SWAP=1
    -DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
    -DBOARD_VIEWE_UEDX48480021_MD80ET
    -DDEBUG_ENABLE_LOADCELL_MOCK=1